### PR TITLE
Changes in README.md to add PR link

### PR DESCRIPTION
**Pull request by Frey0-0**

### CODE REVIEW

**Comment by Frey0-0** [comment]
@developer-diganta please review :) I will add another link in the next [PR](https://github.com/keploy/typescript-sdk/pull/62), it is almost completed.

**Comment by developer-diganta** [comment]
Hi @Frey0-0! There is just one change required. Can you replace the issue icon with the pr icon?
image
`../assets/pr.svg` this is the icon's path.

**Comment by Frey0-0** [comment]
Oh I am sorry @developer-diganta I will change it right now :sweat_smile:

**Review by developer-diganta — APPROVED** [review]
Cool no issues! rtm @nehagup

**Pull request merged**
